### ISSUE TITLE
soup.title AttributeError: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by YUChoe** [YUChoe/noizze_crawler#3]
```
Traceback (most recent call last):
  File "go.py", line 6, in <module>
    (title, desc, image_url, html) = nc.crawler(url)			
  File "/home/pp/Desktop/test/venv/lib/python3.7/site-packages/noizze_crawler.py", line 42, in crawler
    (title, desc, image_url, html) = parser(url, html)
  File "/home/pp/Desktop/test/venv/lib/python3.7/site-packages/noizze_crawler.py", line 54, in parser
    if soup.title.string:
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by YUChoe** [comment]
* https://generative.fm/
* https://www.pramp.com/dashboard#/
